name: upload-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: 上传固件到release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "tag_name"
        files: "./redis-desktop-manager-0.9.3.817.exe"  # 确保文件路径正确
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
